# Constants for plotting
# colorbar
CBAR_EXTENTION = "both"
paint_all = True
WHITE_PART_NUM_FROM_MIDDLE = 2
cbar_auto_ticks = True
CBAR_TICKS_INTERVAL = 20
CBAR_TICKS_BASE = 1
CBAR_LABEL_SIZE = 10
CBAR_LABEL_LOCATION = 3

# contour
CONTOUR_WIDTH = 0.1
CONTOUR_LABEL_SIZE = 5

# vector
VECTOR_MULTIPLIER = 1
# VECTOR_WIDTH = 0.005
# VECTOR_LINEWIDTH = 1.5
# VECTOR_HEADWIDTH = 2.0
# VECTOR_HEADLENGTH = 1.5
# VECTOR_HEADAXIS_LENGTH = 1.5

# gridline
grid_line = False
GRIDLINE_COLOR = "grey"
GRIDLINE_WIDTH = 0.5

# variable information
VAR_INFO_XLOCATION = -0.05
VAR_INFO_YLOCATION = -0.13

# image quality
IMAGE_DPI = 300
