LAT_START = 33
LAT_END = 34
LON_START = 130
LON_END = 131

LAT_LON_RANGE: dict[str, tuple[float, float]] = {
    "lat": (LAT_START, LAT_END),
    "lon": (LON_START, LON_END),
}

LON_TICKS_INTERVAL = 0.1
LAT_TICKS_INTERVAL = 0.1

is_deg_min_format = True


SHADE_VARNAME = "RAINNC"
SHADE_MIN = 0
SHADE_MAX = 1000
SHADE_INTERVAL = 100

COLOR_MAP_NAME = "YlOrRd"
CBAR_EXTENTION = "both"
CBAR_TICKS_INTERVAL = 200
CBAR_TICKS_BASE = 0
CBAR_UNIT = "[m]"
CBAR_LABEL_SIZE = 10
CBAR_LABEL_LOCATION = -10

CONTOUR_MIN = 0
CONTOUR_MAX = 1000
CONTOUR_INTERVAL = 100
CONTOUR_WIDTH = 1
CONTOUR_COLOR = "black"

VECTOR_DENSITY = 15
VECTOR_REDUCTION_SCALE = 3
VECTOR_COLOR = "blue"
VECTOR_LEDEND_VALUE = 5
VECTOR_LEGEND_NAME = f"{VECTOR_LEDEND_VALUE} " + r"[$\mathrm{m/s}$]"

GRIDLINE_COLOR = "grey"
GRIDLINE_WIDTH = 0.5

TITLE_SIZE = 14
