WRFOUT_INTERVAL = 10

LAT_START = 33.006493
LAT_END = 33.797226
LON_START = 129.97696
LON_END = 130.7594

LON_TICKS_INTERVAL = 0.1
LAT_TICKS_INTERVAL = 0.1

is_deg_min_format = False

PRESSURE_PLAIN = 700
TITLE = "dbz"
TITLE_SIZE = 14

shade_plot = True
SHADE_VARNAME = "dbz"
SHADE_MIN = 1
SHADE_MAX = 51
SHADE_INTERVAL = 5
SHADE_MULTIPLIER = 1
SHADE_ADDITION = 0

COLOR_MAP_NAME = "jet"
CBAR_EXTENTION = "max"
paint_all = True
WHITE_PART_NUM_FROM_MIDDLE = 2

CBAR_TICKS_INTERVAL = 20
CBAR_TICKS_BASE = 1
CBAR_UNIT = "[dbz]"
CBAR_LABEL_SIZE = 10
CBAR_LABEL_LOCATION = 3
cbar_auto_ticks = True

contour_plot = True
CONTOUR_VARNAME = "HGT"
CONTOUR_MIN = 150
CONTOUR_MAX = 2150
CONTOUR_INTERVAL = 100
CONTOUR_MULTIPLIER = 1
CONTOUR_ADDITION = 0
CONTOUR_WIDTH = 0.1
CONTOUR_COLOR = "black"
CONTOUR_LABEL_SIZE = 5
plot_contour_label = False
CONTOUR_LABEL_INTERVAL = 2000

vector_plot = False
U_VEXTOR_VARNAME = "uvmet10"
V_VEXTOR_VARNAME = "uvmet10"
VECTOR_DENSITY = 40
VECTOR_REDUCTION_SCALE = 30
VECTOR_COLOR = "palevioletred"
VECTOR_MULTIPLIER = 1
# VECTOR_COLOR = "steelblue"
# VECTOR_WIDTH = 0.005
# VECTOR_LINEWIDTH = 1.5
# VECTOR_HEADWIDTH = 2.0
# VECTOR_HEADLENGTH = 1.5
# VECTOR_HEADAXIS_LENGTH = 1.5

VECTOR_LEDEND_VALUE = 5
VECTOR_LEGEND_NAME = f"{VECTOR_LEDEND_VALUE} " + r"[$\mathrm{m/s}$]"

grid_line = False
GRIDLINE_COLOR = "grey"
GRIDLINE_WIDTH = 0.5

VAR_INFO_XLOCATION = -0.05
VAR_INFO_YLOCATION = -0.125

GIF_INTERVAL_TIME = 150
GIF_NAME = TITLE
MP4_FPS = 5.0
MP4_NAME = TITLE
